# Use an official Nginx image to serve the frontend files
FROM nginx:alpine

# Copy the frontend files (HTML, CSS, JS) to the Nginx HTML directory
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./static/ /usr/share/nginx/html/static/

# Expose port 80 for the Nginx server
EXPOSE 80

