version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile  # Use lowercase 'dockerfile' instead of the default 'Dockerfile'
    container_name: frontend
    ports:
      - "80:80"  # Exposes port 80 for the frontend
    networks:
      - todo-network
    depends_on:
      - backend  # Ensure backend starts before frontend

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile  # Use lowercase 'dockerfile' instead of the default 'Dockerfile'
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todo-db  # MongoDB connection string
    ports:
      - "5000:5000"  # Exposes port 5000 for the backend
    networks:
      - todo-network
    depends_on:
      - mongodb  # Ensure MongoDB starts before backend

  # MongoDB Service
  mongodb:
    image: mongo:latest  # Using the official MongoDB image
    container_name: mongo
    volumes:
      - mongodb-data:/data/db  # Persist MongoDB data
    networks:
      - todo-network
    ports:
      - "27017:27017"  # Expose MongoDB port (optional)

networks:
  todo-network:
    driver: bridge  # Ensure all containers are connected to this network

volumes:
  mongodb-data:
    driver: local  # Persist MongoDB data in a local volume

